on:
  push:
    branches:
    - "**"
    tags:
    - "v*"
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: run tox
      run: tox
      env:
        TOXENV: static

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 3.7
        - 3.8
        - 3.9

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: start rabbitmq
      run: |
        docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq ghcr.io/nameko/nameko-rabbitmq:3.6.6

    - name: install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: run tox
      run: tox
      env:
        TOXENV: py${{ matrix.python-version }}-test

  distribute:
    runs-on: ubuntu-latest
    needs:
    - static
    - test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: generate distributables
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel

    - name: publish to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
